######################################################################
# Automatically generated by qmake (2.00a) Wed Nov 1 23:09:00 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += messager.h
SOURCES += eventloop.cpp messager.cpp
