######################################################################
# Automatically generated by qmake (2.00a) Tue Jun 28 18:51:12 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += matrix.h
SOURCES += matrix.cpp
