version: build{build}

branches:
  except:
    - project/travis

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    releaseName: TableEdit_win64

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - set QTDIR=C:\Qt\5.12\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - qmake
  - nmake
after_build:
  - if "%APPVEYOR_REPO_TAG%"=="true" windeployqt bin\TableEdit.exe --qmldir %QTDIR%\qml
artifacts:
  - path: bin
    name: $(releaseName)
deploy:
  provider: GitHub
  auth_token: $(GITHUB_OAUTH_TOKEN)
  description: 'TableEdit Release'
  draft: false
  prerelease: false
  on:
      APPVEYOR_REPO_TAG: true
