######################################################################
# Automatically generated by qmake (2.00a) Thu Apr 14 21:32:31 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .
include ($$(CPPLIBS)/utils/common.pri)

# Input
HEADERS += logtail.h
SOURCES += logtail.cpp


