######################################################################
# Automatically generated by qmake (2.00a) Fri Aug 5 01:05:24 2005
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inputform.h
SOURCES += inputform.cpp numvalidate.cpp
