######################################################################
# Automatically generated by qmake (2.00a) Mon Nov 28 13:15:19 2005
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fraction.h
SOURCES += copyassign.cpp fraction.cpp
