######################################################################
# Automatically generated by qmake (2.00a) Thu Jun 2 22:33:51 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += moving.h
SOURCES += moving.cpp
